config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
	
	private

		def set_permalink(hex_length)
			self.permalink = loop do
				random = SecureRandom.hex(hex_length)
				break random unless self.class.exists?(permalink: random)
			end
		end  
end

app/models/contact.rb
class Contact < ApplicationRecord

	before_create -> { set_permalink(2) }

	def full_name
		"#{self.first_name} #{self.last_name}".titleize
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact, notice: 'Contact was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /contacts/1
  def update
    if @contact.update(contact_params)
      redirect_to @contact, notice: 'Contact was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /contacts/1
  def destroy
    @contact.destroy
    redirect_to contacts_url, notice: 'Contact was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :mobile, :home_phone, :office_phone, :street_address, :city, :state, :country, :permalink)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@contacts = Contact.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.haml
= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    .field
      = f.label :first_name, :class => 'form-label'
      = f.text_field :first_name, :class => 'form-control'
    .field
      = f.label :last_name, :class => 'form-label'
      = f.text_field :last_name, :class => 'form-control'
  .form-group
    .field
      = f.label :email, :class => 'form-label'
      = f.text_field :email, :class => 'form-control'
    .field
      = f.label :mobile, :class => 'form-label'
      = f.text_field :mobile, :class => 'form-control'
    .field
      = f.label :home_phone, :class => 'form-label'
      = f.text_field :home_phone, :class => 'form-control'
    .field
      = f.label :office_phone, :class => 'form-label'
      = f.text_field :office_phone, :class => 'form-control'
  .from-group
    .field
      = f.label :street_address, :class => 'form-label'
      = f.text_field :street_address, :class => 'form-control'
    .field
      = f.label :city, :class => 'form-label'
      = f.text_field :city, :class => 'form-control'
    .field
      = f.label :state, :class => 'form-label'
      = f.text_field :state, :class => 'form-control'
    .field
      = f.label :country, :class => 'form-label'
      = f.text_field :country, :class => 'form-control'
  %br
  .form-group
    .actions
      = f.submit 'Save', :class => 'btn btn-primary btn-block'

app/views/contacts/edit.html.haml
%h1 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/index.html.haml
%h1 Listing contacts

%table.table
  %thead
    %tr
      %th First name
      %th Last name
      %th Email
      %th Mobile
      %th Home phone
      %th Office phone
      %th Street address
      %th City
      %th State
      %th Country
      %th Permalink
      %th
      %th
      %th

  %tbody
    - @contacts.each do |contact|
      %tr
        %td= contact.first_name
        %td= contact.last_name
        %td= contact.email
        %td= contact.mobile
        %td= contact.home_phone
        %td= contact.office_phone
        %td= contact.street_address
        %td= contact.city
        %td= contact.state
        %td= contact.country
        %td= contact.permalink
        %td= link_to 'Show', contact
        %td= link_to 'Edit', edit_contact_path(contact)
        %td= link_to 'Destroy', contact, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Contact', new_contact_path

app/views/contacts/new.html.haml
%h1 New contact

= render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.haml
%p#notice= notice

%table.table
  %tr
    %td
      %b First name:
    %td
      = @contact.first_name
  %tr
    %td
      %b Last name:
    %td
      = @contact.last_name
  %tr
    %td
      %b Email:
    %td      
      = @contact.email
  %tr
    %td
      %b Mobile:
    %td      
      = @contact.mobile
  %tr
    %td
      %b Home phone:
    %td      
      = @contact.home_phone
  %tr
    %td
      %b Office phone:
    %td      
      = @contact.office_phone
  %tr
    %td
      %b Street address:
    %td      
      = @contact.street_address
  %tr
    %td
      %b City:
    %td      
      = @contact.city
  %tr
    %td
      %b State:
    %td      
      = @contact.state
  %tr
    %td
      %b Country:
    %td      
      = @contact.country
  %tr
    %td
      %b Permalink:
    %td      
      = @contact.permalink

= link_to 'Edit', edit_contact_path(@contact)
\|
= link_to 'Back', contacts_path

app/views/layouts/application.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title ContactList
		= csrf_meta_tags
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
	%body
		.container
			%nav.navbar.navbar-inverse.navbar-fixed-top
				.container
					.navbar-header
						%button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
							%span.sr-only Toggle navigation
							%span.icon-bar
							%span.icon-bar
							%span.icon-bar
						%a.navbar-brand{:href => root_path} contact-list
					#navbar.navbar-collapse.collapse
						%form.navbar-form.navbar-right
							.form-group
								%input.form-control{:placeholder => "search", :type => "text"}/
							%button.btn.btn-success{:type => "submit"} Search	
			%br
			%br
			= yield

app/views/pages/home.haml
.jumbotron
	.container
		%h2 Contacts
		%p
			%a.btn.btn-primary.btn-lg{:href => new_contact_path, :role => "button"} Add		
.container
	/ Example row of columns
	.row
		- @contacts.each do |c|
			.col-md-4
				.panel
					%h2= c.full_name
					%p= c.email
					%p= c.mobile
					%p
						%a.btn.btn-default{:href => contact_path(id: c.id), :role => "button"} View details »

	%hr/
	%footer
		%p © 2017 Company, Inc.